apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cclaude-app
spec:
  destination:
    namespace: dev
    server: 'https://kubernetes.default.svc'
  source:
    path: manifests
    repoURL: 'https://github.com/cclaude42/iot-cclaudeAPP.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
