#  vagrant up
#
#  sudo k3s kubectl get nodes -o wide
#  sudo k3s kubectl get all
#  sudo k3s kubectl get ingress
#  sudo k3s kubectl describe ingress -A
#
#  curl 192.168.56.110
#  curl -H "Host: app1.com" 192.168.56.110
#  curl -H "Host: app3.com" 192.168.56.110
#
#  vagrant destroy -f
#

Vagrant.configure("2") do |config|

  config.vm.define "cclaudeS" do |cclaudeS|
    cclaudeS.vm.box = "debian/bullseye64"
    cclaudeS.vm.hostname = "cclaudeS"
    cclaudeS.vm.network "private_network", ip: "192.168.56.110", bridge: "eth1"
    cclaudeS.vm.synced_folder "./data/", "/data"
    cclaudeS.vm.provider "virtualbox" do |vb|
      vb.name = "cclaudeS"
      vb.cpus = 4
      vb.memory = 2048
    end
    cclaudeS.vm.provision :shell, inline: <<-SHELL
      sudo apt update && sudo apt install curl -qqy
      curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--node-external-ip=192.168.56.110" K3S_TOKEN=verysecret sh -s -
      k3s kubectl apply -f /data/one.yaml
      k3s kubectl apply -f /data/two.yaml
      k3s kubectl apply -f /data/three.yaml
      k3s kubectl apply -f /data/ingress.yaml
    SHELL
  end

end
