#  vagrant up
#
#  vagrant ssh cclaudeS
#  sudo k3s kubectl get nodes -o wide
#
#  vagrant destroy -f
#

Vagrant.configure("2") do |config|

  config.vm.define "cclaudeS" do |cclaudeS|
    cclaudeS.vm.box = "debian/bullseye64"
    cclaudeS.vm.hostname = "cclaudeS"
    cclaudeS.vm.network "private_network", ip: "192.168.56.110", bridge: "eth1"
    cclaudeS.vm.provider "virtualbox" do |vb|
      vb.name = "cclaudeS"
      vb.cpus = 2
      vb.memory = 1024
    end
    cclaudeS.vm.provision :shell, inline: <<-SHELL
      sudo apt update && sudo apt install curl -qqy
      curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--node-external-ip=192.168.56.110" K3S_TOKEN=verysecret sh -s -
    SHELL
  end

  config.vm.define "cclaudeSW" do |cclaudeSW|
    cclaudeSW.vm.box = "debian/bullseye64"
    cclaudeSW.vm.hostname = "cclaudeSW"
    cclaudeSW.vm.network "private_network", ip: "192.168.56.111", bridge: "eth1"
    cclaudeSW.vm.provider "virtualbox" do |vb|
      vb.name = "cclaudeSW"
      vb.cpus = 2
      vb.memory = 1024
    end
    cclaudeSW.vm.provision :shell, inline: <<-SHELL
      sudo apt update && sudo apt install curl -qqy
      curl -sfL https://get.k3s.io | K3S_URL=https://192.168.56.110:6443 K3S_TOKEN=verysecret sh -s -
    SHELL
  end

end